services:
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0:8080
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}?sslmode=disable
      - REDIS_URL=valkey:6379

      - BETATESTERS_ONLY=true
    depends_on:
      - postgresdb
    networks:
      - default

  frontend:
    build:
      context: ./frontend
      args:
        - PUBLIC_BACKEND_URL=http://localhost:8080 # URL of the backend API which should be accessed by clients on the browser
    restart: unless-stopped
    ports:
      - "8088:3000"
    networks:
      - default

  postgresdb:
    image: postgres:17
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    networks:
      - default

  valkey:
    image: valkey/valkey:8
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - valkey_data:/data

volumes:
  db_data:
  valkey_data:

networks:
  default:
    driver: bridge
