// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    userHash, sid
) VALUES (
    $1, $2
)
RETURNING id, userhash, sid
`

type CreateUserParams struct {
	Userhash string
	Sid      string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Userhash, arg.Sid)
	var i User
	err := row.Scan(&i.ID, &i.Userhash, &i.Sid)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, userhash, sid FROM users
WHERE userHash = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, userhash string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, userhash)
	var i User
	err := row.Scan(&i.ID, &i.Userhash, &i.Sid)
	return i, err
}
