volumes:
  db_data:

services:
  db:
    image: postgres:17
    restart: unless-stopped
    ports:
      - 5433:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=ultrasecurepassword
      - POSTGRES_USER=stravule
      - POSTGRES_DB=stravule

  valkey:
    image: valkey/valkey:8
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - ./valkey:/data
